Exception: Customise error page handler
Instead of throw stack to user directly,
customise error page handler and fill it with error reason.

Signed-off-by: Royce Lv <lvroyce@linux.vnet.ibm.com>