bug fix: encode the args in KimchiException when is is unicode.
I create a pool with name "kīмсhīPool"

When libvirt errors with this pool, it will cause the UnicodeDecodeError.

File "/home/shhfeng/work/workdir/kimchi/src/kimchi/model/storagepools.py",
line 401, in delete
    {'name': name, 'err': e.get_error_message()})
File "/home/shhfeng/work/workdir/kimchi/src/kimchi/exception.py", line
37, in __init__
    msg = _messages.get(code, code) % args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 49:
ordinal not in range(128)

Signed-off-by: ShaoHe Feng <shaohef@linux.vnet.ibm.com>