Fix shallow scan test: wait until storage volume creation finished
Shallow scan errors with:
    Traceback (most recent call last):
  File "test_rest.py", line 1272, in test_iso_scan_shallow
    '/storagepools/kimchi_isos/storagevolumes/').read())[0]
  IndexError: list index out of range
Because of shallow scan finished before volume creation finshed.
Since we change creation of volume to async task,
we need to wait it finish before issue shallow scan.

Signed-off-by: Royce Lv <lvroyce@linux.vnet.ibm.com>