Bug fix: Properly encode unicode string
The data sends/receives to server is on unicode format.
So we need to encode it to UTF-8 to get the string representation.

This problem was identified when running Kimchi tests in which the
following error was displayed:

[02/Mar/2016:11:51:42] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/alinefm/wok/src/wok/control/base.py", line 136, in wrapper
    params = {'ident': str(model_args[0])}
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-3: ordinal not in range(128)

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>