Make sure ISO files have read permission while starting VM
libvirt needs to have read permission on cdrom files in order to start
the virtual machine without problems.

Otherwise, the user will get the following error:

$ sudo virsh start aaaa
error: Failed to start domain aaaa
error: internal error process exited while connecting to monitor: kvm:
-drive file=/root/Fedora-Live-Desktop-x86_64-19-1.iso: could not open disk image
/root/Fedora-Live-Desktop-x86_64-19-1.iso: Permission denied

So make sure the ISO file has read permission before starting the
virtual machine.

Signed-off-by: Aline Manera <alinefm@br.ibm.com>