bug fix: Properly display missing parameter
The exception instance was being used as the missing parameter what is
causing errors like below:

TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found

To fix use the string representation for the exception instance.

Signed-off-by: Aline Manera <alinefm@br.ibm.com>