Need root privilege to run test_vm_list_sorted test
When the test case was run by a common user, following
errors displayed:
ERROR: test_vm_list_sorted (test_model.ModelTests)
---------------------------------------------
  File "/usr/lib64/python2.7/site-packages/libvirt.py",
  line 236, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirtError: authentication failed: polkit:
polkit\56retains_authorization_after_challenge=1
Authorization requires authentication but no agent is available.

Signed-off-by: Shu Ming <shuming@linux.vnet.ibm.com>