Exception: move exceptions from model
Exceptions in model results in circular import which may introduce
errors in the future, put them in a single module.

Signed-off-by: Royce Lv <lvroyce@linux.vnet.ibm.com>