isoinfo: Add default value for ignore_list paramter
ignore_list parameter was added to avoid displaying duplicated results during
deep scan.
So isoinfo main program must be updated accordingly or it will raise the
following error:

$ python kimchi/isoinfo.py http://localhost/Fedora-Live-Desktop-x86_64-19-1.iso
Traceback (most recent call last):
  File "kimchi/isoinfo.py", line 343, in <module>
    probe_iso(None, dict(path=sys.argv[1], updater=updater))
  File "kimchi/isoinfo.py", line 283, in probe_iso
    ignore_list = params['ignore_list']
KeyError: 'ignore_list'

Signed-off-by: Aline Manera <alinefm@br.ibm.com>