bug fix: Make URI parameter is not None before encoding it
The following error is raised when the user tried to reboot the host
system:

Request Headers:
  AUTHORIZATION: Basic YWxpbmVmbTowaG5lKjI4ZGljSA==
  Content-Length: 2
  HOST: localhost:8000
  Remote-Addr: 127.0.0.1
  ACCEPT: application/json
  USER-AGENT: curl/7.27.0
  Content-Type: application/json
[25/Feb/2014:14:05:28] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/alinefm/kimchi/src/kimchi/control/base.py", line 79, in wrapper
    for arg in self.model_args])
AttributeError: 'NoneType' object has no attribute 'encode'

It is because /host resource has no parameter and fails to encode() the
None value.
So fix it by verifying the parameter is not None in order to make the
encode() call.

Signed-off-by: Aline Manera <alinefm@br.ibm.com>